HOSTS:
  centos-72-x64:
    roles:
      - agent
      - default
    platform: el-7-x86_64
    box: gutocarvalho/centos7x64
    hypervisor: vagrant
    vagrant_memsize: 2600

CONFIG:
  type: aio
